version: '3.8'
services:
  dev-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookmarks
    ports:
      - "5434:5432"
    networks:
      - app-network
networks:
  app-network:
